### ISSUE TITLE
Running Helm without Temporal

### ISSUE THREAD

**Issue by domhandy** [dittofeed/dittofeed#1252]
I am trying to run dittofeed without temporal. I am getting this error message:

```
{"level":30,"time":1736848679256,"service.version":"bf9b8a2","msg":"Skipping bootstrap"}
TransportError: tonic::transport::Error(Transport, ConnectError(ConnectError("tcp connect error", Os { code: 99, kind: AddrNotAvailable, message: "Cannot assign requested address" })))
    at NativeConnection.connect (/service/node_modules/@temporalio/worker/lib/connection.js:56:23)
    at async Promise.all (index 0)
```

I am using terraform. My values.yaml.tpl file:

```
postgresql:
  enabled: false

clickhouse:
  enabled: false
temporal:
  enabled: false

env:
  - name: DATABASE_HOST
    value: ${pg_ip}
  - name: DATABASE_USER
    value: ${pg_user}
  - name: DATABASE_PASSWORD
    value: ${pg_password}

  # Instead of a static DNS name, we insert the IP from Terraform
  - name: CLICKHOUSE_HOST
    value: "http://${clickhouse_ip}:8123"
  - name: CLICKHOUSE_USER
    value: "default"
  - name: CLICKHOUSE_PASSWORD
    value: ""
  - name: BOOTSTRAP_SAFE # BOOTSTRAP should be set to "false" after the first deployment
    value: "true"
    ```
